### ISSUE TITLE
Removed role count is not correct

### ISSUE THREAD

**Issue by diogotcorreia** [ist-bot-team/ist-discord-bot#103]
![image](https://user-images.githubusercontent.com/7467891/196044354-73e1228b-71a1-416f-967a-0c3be79b0629.png)
![image](https://user-images.githubusercontent.com/7467891/196044375-b5d6b713-fecf-4bad-8313-f38c32f5c9af.png)

#101 

Seems to be doubling the count (if it removes 1 role it says 2, if it removes 2 it says 4)

**Comment by RafDevX** [comment]
This happens if two or more degrees share a course selection channel (i.e., LEIC-A and LEIC-T); the Prisma query below returns one result for each degree, resulting in $\text{rolesToRemove.length} = \text{nr. roles} \times \text{nr. degrees}$.

https://github.com/ist-bot-team/ist-discord-bot/blob/1df87dfa83479b1dd995f1e0ad8295701c64d2c6/src/modules/courses.ts#L838-L850

Filtering out duplicate role IDs should fix it.
