### ISSUE TITLE
Gallery Channels are broken

### ISSUE THREAD

**Issue by RageKnify** [ist-bot-team/ist-discord-bot#110]
All messages from non-admins are deleted by the bot in gallery channels even if they are images or URLs, the function is identified below

https://github.com/ist-bot-team/ist-discord-bot/blob/9c521aafcb06c8c339e31ec5879cdf7462b1638e/src/modules/galleryChannels.ts#L11-L48

**Comment by RafDevX** [comment]
This is due to a missing gateway (privileged) intent, `MESSAGE_CONTENT`, that allows accessing content fields in the `Message` object, per [the docs](https://discord.com/developers/docs/topics/gateway#message-content-intent).

The fix is therefore to enable the privileged intent on the application's settings on Discord's Developer Portal and then to declare the intent in question on bot startup.
